//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsMaster
    {
        public long ExpenseID { get; set; }
        public Nullable<long> UserID { get; set; }
        public int CategoryID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> SpendingDate { get; set; }
        public Nullable<short> CurrencyID { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual CurrenyMaster CurrenyMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
